from enum import StrEnum


class AgentState(StrEnum):
    IDLE = "IDLE"
    RUNNING = "RUNNING"
    SEARCHING = "SEARCHING"
    FILTERING = "FILTERING"
    ANALYZING = "ANALYZING"
    APPLYING = "APPLYING"
    PAUSED = "PAUSED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    SECURITY_REQUIRED = "SECURITY_REQUIRED"
    AI_QUOTA_EXHAUSTED = "AI_QUOTA_EXHAUSTED"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"
    STOPPED = "STOPPED"
    CRITICAL_ERROR = "CRITICAL_ERROR"
